### PR TITLE
Store sessions in memory, and remove all the sequelize/postgres stuff!

### PR DESCRIPTION
**Pull request by camjackson**
This should be merged *after* #154.

This converts the session storage to be in-memory, rather than in the database.

That was the final thing that was using the database, so lumped in with this is also the removal of all the postgres bits and pieces. Very exciting! 😄

### CODE REVIEW

**Comment by camjackson** [comment]
Not sure why the build is failing on this. Will come back to it once #154 has been merged.

**Comment by camjackson** [comment]
Fixed the build! 😄

**Comment by phazel** [comment]
As we talked about in Slack, we should talk when the time comes about how we want to deal with handling the session once we start scaling and there's more than one core container going. Will that be an issue? We don't know yet, it'll be an adventure!

Also, the DB still exists in the infra repo (and in real life), so we'll need to remove that as the final-final step.

**Comment by phazel** [comment]
As we talked about in Slack, we should talk when the time comes about how we want to deal with handling the session once we start scaling and there's more than one core container going. Will that be an issue? We don't know yet, it'll be an adventure!

Also, the DB still exists in the infra repo (and in real life), so we'll need to remove that as the final-final step.

**Pull request merged**
