### PR TITLE
Dockerise the dev environment some more

### PR DESCRIPTION
**Pull request by camjackson**
This is a continuation of the work on #129, which we started at the last hack day.

- It adds a barebones development Dockerfile, and changes the docker-compose config to be more development-oriented. My assumption here is that we're only using docker-compose locally to make development easier, and not for production. In prod, most of the extra bits and pieces that we need to connect to are external AWS resources, so compose doesn't make a lot of sense there.
- It makes the `go.sh` script a bit smarter, so that you can either use it for an interactive shell to develop in, or you can run one-off commands (like `npm test`) in a container. This might be useful for creating a dockerised build pipeline.
- I also changed the db config/connection stuff so that in dev/test mode, it will use a DB connection string from the environment if one is supplied, because that's how the docker-compose stuff works. I still left the old config there though (see below).

This PR is quite conservative, in that I've tried to make the docker dev setup easier, without removing/breaking the old vagrant setup. If we're happy to go all-in with this way of doing things, then there's a bunch of cleanup we can do:

- Simplify the db connection stuff to always use an connection string from an environment variable
- Remove all the ansible code
- Remove the Vagrantfile and any other Vagrant stuff
- Clean up the bin scripts (haven't looked that deeply into this but I'm pretty sure most of them can go away)

Stuff I haven't done:
- Experimented with file watching to see if stuff like nodemon, `mocha --watch` or WDS hot-loading will work
 - In fact I haven't touched the frontend development stuff at all. Right now you'd need to manually rebuild the assets each time. Not sure how to manage that...
 - Composing it with all the other dependencies we're about to have. I.e. kinesalite, locally running lambdas, etc. That becomes very high priority work once #123 is merged.

### CODE REVIEW

**Comment by camjackson** [comment]
Now that #123 has been merged, we need the other bits docker-composerised. I'm working on that now.

**Comment by camjackson** [comment]
Ready for review! Should be as easy as `./go.sh` to start everything up, with an interactive shell where you can then do `npm start`. Or you can just do a single command, e.g. `./go.sh npm start` or `./go.sh npm test`.

**Comment by pameck** [comment]
Cloned the repo and ran `./go.sh`, all good now! Let's merge this!

**Comment by pameck** [comment]
Smoothest RR setup so far, nice one @camjackson and @phazel

**Comment by camjackson** [comment]
:D

**Pull request merged**
