### PR TITLE
119

### PR DESCRIPTION
**Pull request by yearofthedan**
This resolves an issue with admins and network admins being able to navigate to each others' views by introducing user type restrictions on the front end. Previously only the backend had this level of granularity. 

Additionally, this fix merges the two dashboards into one in order to reduce duplication.  

see [issue 119](https://github.com/rabblerouser/rabblerouser-core/issues/119) for more info.

### CODE REVIEW

**Comment by pameck** [comment]
Reviewed the code, haven't been able to manually test it as I have a problem creating the VM. I'm merging it anyway, if we run into problems we can fix them on master.

**Comment by camjackson** [comment]
Just had a look at this too, out of curiosity. Looks awesome. It was fun reading the commits building all the little bits together, then seeing the big payoff at the end as the two views merge into one! 

👯 =>💃 

There's just one problem - when you log in as a super user, the backend still tries to redirect you to the old route. I'll quickly take that out now, it's just a couple of lines.

**Comment by camjackson** [comment]
Actually there's some weird errors happening, needs more investigation. I'll look again tomorrow if no one else gets to it.

But right now the app is slightly broken (including in staging) if you log in as a super admin. You can just change the URL manually though, and everything seems to work.

**Comment by yearofthedan** [comment]
That's interesting. If I remove the check for user type on login success and just redirect to dashboard it works for both admin and super admin for me. Is [this](https://github.com/rabblerouser/rabblerouser-core/blob/master/backend/src/security/loginHandler.js) where you were changing?

**Comment by camjackson** [comment]
Yeah I changed that bit and then the redirect worked fine. But for some reason the app then shows me the "There was an error when contacting the server" red error box at the top of the screen, and data doesn't seem to load. Possibly just my problem, I'll dig a little deeper.

**Comment by camjackson** [comment]
Ah, the problems seems to be that the user cookie isn't being set. All I have is `connect.sid`.

**Comment by camjackson** [comment]
Ohh, I know why. It's because when you run it locally with the webpack dev server, the backend doesn't get hit at all when you request `/dashboard` -- the WDS handles the request. So the cookie doesn't get set when loading the frontend.

So with the redirect fixed, the deployed app will work fully. But the local dev workflow is a bit off.

**Comment by yearofthedan** [comment]
Ah I see. I haven't been using the webpack dev server as part of my workflow.

**Comment by yearofthedan** [comment]
Hoping this is resolved in https://github.com/rabblerouser/rabblerouser-core/commit/8c82bc2c23327b229c5c86bffe6c149da4ae1a33 
@camjackson can you have a look and let me know?

**Comment by camjackson** [comment]
Will do.

**Comment by camjackson** [comment]
Yeah that works fine now.

It does mean that the WDS setup depends on the html assets having been copied to the backend at least once, although we kind of already have that restriction because the backend crashes at startup if the favicon hasn't been copied over. Also, if you're working on the html files (rare), then you'll need to rerun the copy_assets.sh script each time you make a change. Not a big deal.

I guess this does highlight that this approach (getting the user type out of a cookie which is set upon fetch of the frontend), might not work long term. As it is now, you couldn't fetch all the static frontend assets from a dumb nginx/cloudfront thing, because we have the download of the frontend coupled to something only the backend can do -- look up the user type.

Not sure what the right approach would be (an extra API call?), and it's fine for now, but just something to think about :)

**Pull request merged**
